import type { ProjectItem } from "@/types/project";

export const projects: ProjectItem[] = [
  {
    id: "motobuket",
    title: "MotoBuket - Smart Car Service Mobile Application",
    category: "Flutter Mobile Application",
    description:
      "A smart car service application that allows users to discover services, find vendors, and request vehicle maintenance services.",
    technologies: ["Flutter", "Dart", "REST API", "Firebase", "Dio", "Git", "Postman"],
    features: [
      "User authentication",
      "Service categories",
      "Vendor search",
      "Location based services",
      "API integration",
      "Responsive UI",
      "Booking workflow",
    ],
    challenges: [
      "API integration and authentication handling",
      "Vendor filtering logic",
      "State management",
      "Production UI development",
    ],
    githubUrl: "https://github.com",
    demoUrl: "https://example.com",
    featured: true,
    imageAlt: "MotoBuket mobile app interface",
  },
  {
    id: "expense-tracker",
    title: "Expense Tracker App",
    category: "Flutter App",
    description: "A personal finance app that organizes spending and helps users stay in control of their budget.",
    technologies: ["Flutter", "Firebase", "SQLite"],
    features: ["Expense logging", "Category insights", "Local storage", "Clean dashboard"],
    githubUrl: "https://github.com",
    demoUrl: "https://example.com",
    imageAlt: "Expense tracker app dashboard",
  },
  {
    id: "weather-app",
    title: "Weather Application",
    category: "Flutter App",
    description: "A weather experience with location-based forecasts and intuitive visuals.",
    technologies: ["Flutter", "REST API"],
    features: ["Live weather", "Location search", "Forecast cards", "Responsive layout"],
    githubUrl: "https://github.com",
    imageAlt: "Weather app interface",
  },
  {
    id: "chat-app",
    title: "Chat Application",
    category: "Flutter App",
    description: "A lightweight messaging application with real-time conversations and a smooth experience.",
    technologies: ["Flutter", "Firebase"],
    features: ["Real-time messaging", "Authentication", "Conversation list", "Modern UI"],
    githubUrl: "https://github.com",
    imageAlt: "Chat application interface",
  },
  {
    id: "portfolio-site",
    title: "Portfolio Website",
    category: "Web App",
    description: "A modern portfolio site built with Next.js and a polished developer-first layout.",
    technologies: ["Next.js", "TypeScript", "Tailwind CSS"],
    features: ["Responsive sections", "SEO-ready", "Motion effects", "Accessible UI"],
    githubUrl: "https://github.com",
    demoUrl: "https://example.com",
    imageAlt: "Portfolio website preview",
  },
];
